# Generated by Django 6.0.5 on 2026-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
